# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=50000']
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        exclude: 'notebooks/'
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: main
    hooks:
      - id: isort
        exclude: 'notebooks/'
        args:
          - --profile
          - black
  - repo: https://github.com/mwouts/jupytext
    rev: v1.12.0
    hooks:
      - id: jupytext
        args: [--sync, --pipe, black, --pipe, 'isort - --treat-comment-as-code "# %%" --float-to-top']
        additional_dependencies:
            - black==21.9b0 # Matches hook
            - isort
