name: {{ cookiecutter.project_name.lower().replace(' ', '_') }}
channels:
  - conda-forge
dependencies:
  - python=3.8
  # IDE
  - jupyter
  - jupyterlab
  - nb_conda_kernels # switch conda envs in jupyter
  # Input/Output
  - netcdf4
  # Numerics
  - numpy
  - pandas
  - scipy
  - xarray
  # Performance
  - bottleneck
  - dask
  - numba
  # Project Management
  - black
  - coveralls
  - flake8
  - isort
  - pre-commit
  - pytest # REQUIRED, DO NOT REMOVE
  - pytest-sugar
  # Regridding
  # Currently, xesmf breaks with esmpy v8.0.0. There is an issue with PIO and MPI.
  # See e.g. https://github.com/conda-forge/esmpy-feedstock/issues/28
  - esmpy<=7.1.0
  - xesmf
  # Statistics
  - eofs
  - xskillscore
  # Visualization
  - cartopy
  - matplotlib
  - nc-time-axis
  - pip
  - pip:
    - pytest-tldr
    - git+https://github.com/bradyrx/esmtools
