[tool.poetry]
name = "cookiecutter-data-science"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
authors = ["Matthieu Mazzolini <m.mazzolini@kayrros.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^0.25.1"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.10.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
  | doc
)/
'''

