[tool.poetry]
name = "{{ cookiecutter.repo_name }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
authors = [ "{{ cookiecutter.author_name }}" ]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^0.19.0"
click = "^8.0.1"
jupyter = "^1.0.0"
pandas = "^1.3.2"
psycopg2 = "^2.9.1"
fastparquet = "^0.7.1"
pyarrow = "^5.0.0"
jupyterlab = "^3.1.7"
dvc = {extras=["s3"], version="^2.8.3"}
cf-data-tools = { git = "git+ssh://git@github.com/contentful/cf-data-tools" }

[tool.poetry.dev-dependencies]
jupytext = "^1.12.0"
black = {extras = ["d"], version = "^21.7b0"}
pytest = "^6.2"
pre-commit = "^2.13"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'

{% if cookiecutter.python_interpreter == 'poetry' %}
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
{% endif %}
