
name: tests

on:
  push:
    branches: [master, v2]
  pull_request:
    branches: [master, v2]
  schedule:
    # Run every Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            dev-requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make requirements

      - name: Lint
        run: |
          make lint

  tests:
    name: Tests (${{ matrix.os }}, Python ${{ matrix.python-version }})
    needs: code-quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"] #[3.7, 3.8, 3.9, "3.10", "3.11"]
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            dev-requirements.txt

      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          cache-downloads: true


      - name: Setup for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          # Install GNU make
          choco install --verbose make
          # Add bundled conda to PATH
          # echo "${CONDA}\Scripts" >> $GITHUB_PATH
          # Add micromamba to PATH
          echo "C:\Users\runneradmin\micromamba-bin\" >> $GITHUB_PATH
          # Set executable paths
          echo "CONDA_EXECUTABLE=micromamba" >> "$GITHUB_ENV"
          echo "CONDA_SHELL_HOOK=micromamba shell hook --shell bash" >> "$GITHUB_ENV"
          echo "BASH_EXECUTABLE=$(which bash)" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make requirements

      - name: Check dependencies
        run: |
          echo $BASH_EXECUTABLE
          $BASH_EXECUTABLE --version
          which make
          make --version
          echo $CONDA_EXECUTABLE
          $CONDA_EXECUTABLE --version
          which pipenv
          pipenv --version
          which virtualenv
          virtualenv --version

      - name: Run tests
        run: |
          make test
